### ISSUE TITLE
Readme update with NPM/React examples

### ISSUE THREAD

**Issue by ryancolorcafe** [MyUNiDAYS/unidays-javascript#45]
I'm finding it hard to import the npm package and make the call to use the `UnidaysTracking` function in a React app. Can you provide an example?

I've tried variations of the following:

```
import { UnidaysTracking } from 'unidays-javascript';

const unidays = new UnidaysTracking(
  'SECRETCODEHERE',
  'USD',
  UNIQUEID,
  'DISCOUNTCODEHERE'
);
unidays.trackingScriptRequest(totalValue);
```

```
import Unidays from 'unidays-javascript';

const unidays = new Unidays.UnidaysTracking(
  'SECRETCODEHERE',
  'USD',
  UNIQUEID,
  'DISCOUNTCODEHERE'
);
unidays.trackingScriptRequest(totalValue);
```

I keep getting an error like: `unidays_javascript__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor`.

Any help on this would be much appreciated, thanks.

**Comment by ryancolorcafe** [comment]
I've also tried importing it like so with no luck so far:

`import UnidaysTracking from 'unidays-javascript/dist/unidays-tracking.min.js';`

and

`import { UnidaysTracking } from 'unidays-javascript/dist/unidays-tracking.min.js';`

**Comment by Danny-UKDM** [comment]
Hi @ryancolorcafe apologies for the rather late reply here.

Firstly, I'm afraid this type of npm-based Javascript development is not a strong suit for the engineers here at UNiDAYS, so unfortunately there isn't much knowledge we can provide around importing this package from npm directly into a React application. 

I personally suspect that we may have an issue with how the package.json is written, in that it's not providing a suitable entry point to the function when it's imported. I am currently in the process of testing this theory with colleagues.  (We are also more than happy to accept a PR if you happen to notice what could be causing the issue here.)

We do, however, have a version of this library available in Node.JS which is also hosted on NPM, please find that here: https://github.com/MyUNiDAYS/unidays-node

Please do let us know if the node package works as expected for you, and of course feel free to respond here if you have further questions.

**Comment by ryancolorcafe** [comment]
@Danny-UKDM thanks for your response, I totally understand. I was able to go the Google Tag Manager route instead.
